---
name: HTML-Adsense
version: 0.1
author:
  - 'Nick Gerakines <nick@gerakines.net>'
abstract: Create adsense widgets easily
license: perl
build_requires:
  Class::Accessor: 0
  Test::More: 0
provides:
  HTML::Adsense:
    file: lib/HTML/Adsense.pm
    version: 0.1
generated_by: Module::Build version 0.2612
