# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Iterator-RoundRobin
version:      0.2
version_from: lib/Iterator/RoundRobin.pm
installdirs:  site
requires:
    English:                       0
    overload:                      0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
