---
name: Net-FeedBurner
version: 0.11
author:
  - 'Nick Gerakines <nick@socklabs.com>'
abstract: The great new Net::FeedBurner!
license: perl
requires:
  English: 0
  LWP::UserAgent: 0
  XML::Simple: 0
build_requires:
  Test::More: 0
  Time::Format: 0
  URI::Escape: 0
  URI::Split: 0
provides:
  Net::FeedBurner:
    file: lib/Net/FeedBurner.pm
    version: 0.11
generated_by: Module::Build version 0.2612
