--- #YAML:1.0
name: WWW-Yahoo-KeywordExtractor
version: 0.03
author:
  - Nick Gerakines <nick@socklabs.com>
abstract: Get keywords from summary text via the Yahoo API
license: perl
generated_by: Module::Build version 0.2612, without YAML.pm
