--- #YAML:1.0
name: Test-NoTabs
version: 0.3
author:
  - Nick Gerakines <nick@socklabs.com>
abstract: Check the presence of tabs in your project
license: perl
generated_by: Module::Build version 0.2612, without YAML.pm
