---
abstract: 'Check the presence of tabs in your project'
author:
  - 'Nick Gerakines <nick@socklabs.com>'
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Test::NoTabs
name: Test-NoTabs
no_index:
  directory:
    - inc
    - t
requires:
  File::Find: 0
  File::Spec: 0
  FindBin: 0
  Test::Builder: 0
  Test::Group: 0
  Test::More: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.4
