---
name: Net-Geohash
version: 1.0
author:
  - 'Nick Gerakines <nick@gerakines.net>'
abstract: The great new Net::Geohash!
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  LWP::UserAgent: 0
build_requires:
  Test::More: 0
  Test::Warn: 0
provides:
  Net::Geohash:
    file: lib/Net/Geohash.pm
    version: 1.0
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
