---
name: WWW-Search-Feedster
version: 0.03
author:
  - 'Nick Gerakines <nick@socklabs.com>'
abstract: Search Feedster
license: perl
requires:
  Carp: 0
  LWP::UserAgent: 0
  Test::More: 0
  WWW::Search: 0
  XML::Simple: 0
provides:
  WWW::Search::Feedster:
    file: lib/WWW/Search/Feedster.pm
    version: 0.03
generated_by: Module::Build version 0.2611
