--- #YAML:1.0
name: WWW-NameGen
version: 0.01
author:
  - Nick Gerakines <nick@socklabs.com>
abstract: A website polling random name generator
license: perl
generated_by: Module::Build version 0.2612, without YAML.pm
