# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Search-UrbanDictionary
version:      0.01
version_from: UrbanDictionary.pm
installdirs:  site
requires:
    SOAP::Lite:                    0.60
    Test::More:                    0.01
    WWW::Search:                   2.35

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
