# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Wow-RealmStatus
version:      0.3
version_from: lib/WWW/Wow/RealmStatus.pm
installdirs:  site
requires:
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
